### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by DC7IA** [aicodix/modem#1]
Please consider submitting your app to F-Droid. :)

**Comment by xdsopl** [comment]
Sorry, but this is not an Android app.

**Comment by DC7IA** [comment]
Oh, sorry. Looked like one here: https://www.reddit.com/r/amateurradio/comments/qvcx64/glad_to_see_that_my_open_source_cofdmtv_stuff/

This repo was linked and also Play Store. :)
