### ISSUE TITLE
Original and decoded files differ

### ISSUE THREAD

**Issue by ea4nz** [aicodix/modem#12]
Hi,

I am having an issue using modem code in short branch. 
I cannot use diff command to compare the original text file and decoded file. 

The input file:

netbsd-raspa$ cat text_2_encode.txt
cadena de prueba para codificar que es un infierno de larga

Encoding and decoding commands:

netbsd-raspa$ ./encode encoded.wav 8000 16 1 text_2_encode.txt
real PAPR: 7.98158 .. 10.1444 dB

netbsd-raspa$  ./decode text_decoded.txt encoded.wav
symbol pos: 2330
coarse cfo: 1500 Hz
oper mode: 16
call sign: ANONYMOUS
demod .... done
coarse sfo: -0.0737413 ppm
finer cfo: 1500 Hz
Es/N0 (dB): 35.7273 35.8356 31.9839 30.681
bit flips: 0

The input and decoded files appear the same:

netbsd-raspa$ cat text_2_encode.txt
cadena de prueba para codificar que es un infierno de larga
netbsd-raspa$ cat text_decoded.txt
cadena de prueba para codificar que es un infierno de larga

But both files have different size:

netbsd-raspa$ ls -lh text*
-rw-r--r--  1 ramiro  users   60B Feb 29 10:09 text_2_encode.txt
-rw-r--r--  1 ramiro  users   85B Feb 29 10:09 text_decoded.txt

So diff command say they differ

netbsd-raspa$ diff text_2_encode.txt text_decoded.txt
Binary files text_2_encode.txt and text_decoded.txt differ

Looking at text_decoded.txt file with Vim editor, it shows something like this:

cadena de prueba para codificar que es un infierno de larga
^@^@^@^@^@^@^@^@

"text_decoded.txt [noeol]"
*****************************************************************

Even more strange:

If I change the input string to something slightly different, changing two characters:

netbsd-raspa$ cat text_2_encode.txt
cadena de prueba para codificar que es un infieebo de larga

netbsd-raspa$         ./encode encoded.wav 8000 16 1 text_2_encode.txt
real PAPR: 7.98158 .. 11.1614 dB

netbsd-raspa$  ./decode text_decoded.txt encoded.wav
symbol pos: 2330
coarse cfo: 1500 Hz
oper mode: 16
call sign: ANONYMOUS
demod .... done
coarse sfo: -0.0939333 ppm
finer cfo: 1500 Hz
Es/N0 (dB): 30.6984 30.5499 31.338 31.4607
payload decoding error.

Decoded text is 0 B size:

netbsd-raspa$ ls -lh text*
-rw-r--r--  1 ramiro  users   60B Feb 29 10:21 text_2_encode.txt
-rw-r--r--  1 ramiro  users    0B Feb 29 10:21 text_decoded.txt

Sure I am missing something but I am not able to find it.
Thanks in advance.
Ramiro.

**Comment by xdsopl** [comment]
You see two different problems there ..

## Diff only works when both files have the exact same size:

> -rw-r--r-- 1 ramiro users 60B Feb 29 10:09 text_2_encode.txt
> -rw-r--r-- 1 ramiro users 85B Feb 29 10:09 text_decoded.txt

```decode``` creates a 85 byte file while the file you used to ```encode``` only has 60 bytes.
So you should zero-pad your file if you want to use diff:
```dd if=/dev/zero of=text_2_encode.txt bs=1 seek=60 count=25```

## Oversaturation of the fixed-point polar list decoder at high SNR:

Usually we do not have this problem with real transmissions, as the SNR estimation will always be lower, and we have "fair" AWGN, so destructive oversaturation in the decoder is unlikely. I've already fixed that problem with 3112e07854ecd01b483dc20e79fb871c4a969591 and you should update your local copy if you want to continue playing with "perfect" signals.

**Comment by ea4nz** [comment]
Many thanks for the detailed explanation. I understand it better now.
Regards

**Comment by xdsopl** [comment]
Just found out that the limit I've chosen is not low enough to handle corner cases, so I've lowered it even further in 4d64b30affd1100afab80b72f9245cc1ae643c7a to avoid the oversaturation. Please check it out.

**Comment by xdsopl** [comment]
Oh wow, the limit of 32 was actually okay with clang and the gcc cross-compilers for ARMv7 and AARCH64, but not for x86_64! Disabling AVX via ```-mno-avx -mno-avx2``` helps get rid of the problem. Need to investigate further ..

**Comment by xdsopl** [comment]
Hmm, forcing the list size to 32, the gcc cross-compilers give the same problem with ARMv7 and AARCH64

**Comment by xdsopl** [comment]
Replacing std::nth_element with std::sort in the polar list decoder seems to fix the problem when using the gcc compiler. Omitting ```-stdlib=libc++``` with clang produces the same problem, which reinforces the theory that there must be a problem with the std::nth_element implementation in the gcc standard template library.

**Comment by xdsopl** [comment]
Or maybe not: std::nth_element is doing a non-stable partial sort in the gcc std lib, while std::nth_element in clang does a stable one. Doing a non-stable sort is allowed AFAIK in the standard, so all is good and the new limit is good.

**Comment by ea4nz** [comment]
Hello Ahmet:

I have updated the source:

netbsd-raspa$ git branch
* short

netbsd-raspa$ git log

commit 8fb7a2aeb896501a472c75a40f9a2e6f898e695c (HEAD -> short, origin/short)
Author: Ahmet Inan <xdsopl@gmail.com>
Date:   Thu May 11 09:06:40 2023 +0200

    added aarch64 example

commit 4d64b30affd1100afab80b72f9245cc1ae643c7a
Author: Ahmet Inan <xdsopl@gmail.com>
Date:   Fri Mar 1 09:14:49 2024 +0100

    lower factor even further to improve corner cases

commit 459ef628c5d86ccd39d1518e363a77f2a0ade905
Author: Ahmet Inan <xdsopl@gmail.com>
Date:   Fri Mar 1 09:06:00 2024 +0100

    made gcc happy

commit 3112e07854ecd01b483dc20e79fb871c4a969591
Author: Ahmet Inan <xdsopl@gmail.com>
Date:   Wed Feb 21 11:28:35 2024 +0100

    avoid oversaturation decoder errors at high SNR

...
...

I have tested both, gcc and clang and fails decoding with both compilers:

	echo "cadena de prueba para codificar que es un infieebo de larga" > text_2_encode.txt
	./encode encoded.wav 8000 16 1 text_2_encode.txt
	./decode text_decoded.txt encoded.wav


doing  1 tests ...
test number: 0 ...
real PAPR: 7.98158 .. 11.1614 dB
symbol pos: 2330
coarse cfo: 1500 Hz 
oper mode: 16
call sign: ANONYMOUS
demod .... done
coarse sfo: -0.0939333 ppm
finer cfo: 1500 Hz 
Es/N0 (dB): 30.6984 30.5499 31.338 31.4607
payload decoding error

netbsd-raspa$ ls -lh text*
-rw-r--r--  1 ramiro  users   60B Mar  1 20:23 text_2_encode.txt
-rw-r--r--  1 ramiro  users    0B Mar  1 20:23 text_decoded.txt


My operating system is NetBSD running in a Raspberry Pi Zero W.

netbsd-raspa$ uname -a
NetBSD netbsd-raspa 10.0_RC3 NetBSD 10.0_RC3 (RPI) #0: Tue Jan 16 08:28:51 UTC 2024  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/evbarm/compile/RPI evbarm

Thanks.

**Comment by xdsopl** [comment]
Can you please give me that exact encoded.wav file, so I can reproduce the problem?

**Comment by xdsopl** [comment]
Also, you need to update your local copy of the ```code``` repository

**Comment by ea4nz** [comment]
Yes, I also updated code repository. I send the encoded file for you.

https://ea4nz.cloudns.cc/hamradio/encoded.wav

**Comment by xdsopl** [comment]
Thanks. Interestingly, this still gives a decoding error even with the new limit and gcc. With clang the decode works fine.

**Comment by xdsopl** [comment]
Thank you so much for your feedback. I was able to improve the polar list decoder further with: https://github.com/aicodix/code/commit/ed9521ba4b26d59b55515a903fc3b816507e1b6d

It is now decoding your encoded file both in gcc and clang without problems.

**Comment by ea4nz** [comment]
Hello Ahmet:

netbsd-raspa$ ./test2.sh
doing  1 tests ...
test number: 0 ...
real PAPR: 7.98158 .. 11.1614 dB
symbol pos: 2330
coarse cfo: 1500 Hz 
oper mode: 16
call sign: ANONYMOUS
demod .... done
coarse sfo: -0.0939333 ppm
finer cfo: 1500 Hz 
Es/N0 (dB): 30.6984 30.5499 31.338 31.4607
bit flips: 0

netbsd-raspa$ ls -lh text*
-rw-r--r--  1 ramiro  users   60B Mar  2 13:51 text_2_encode.txt
-rw-r--r--  1 ramiro  users   85B Mar  2 13:51 text_decoded.txt

It works now! Many thanks!
Regards.
Ramiro.
