### ISSUE TITLE
Question : Streaming feature

### ISSUE THREAD

**Issue by LieBtrau** [aicodix/modem#14]
Hi,
This might not be the right place to ask for features, but I don't know of any other way.

Are there plans to add (audio) streaming features to this modem? Instead of large packets, a sequence of small packets would need to be encoded.  To save bandwidth, the callsign and mode only need to be sent once (before the first packet in the sequence).  If possible, the OFDM-synchronisation sequence would also be needed once.

e.g. Codec2-1200 uses packets of 48bits, at 40ms intervals.

The tests I've done with HT's using this modem learn me that achieving a net bandwidth of 1200bps is no problem (e.g. in mode 11).  It's the high packet size (causing delay) that make it unsuitable for streaming.

Currently polar codes are being used, but for higher packet sizes.  I have no idea if polar codes can be used with much smaller packets. sizes.

Regards,

Christoph

**Comment by xdsopl** [comment]
It is all open source. I've planted the seeds, so let's hope the weather is right and the soil nutritious.

The SCL decoder I've implemented can go pretty far if you need short codes:

https://github.com/aicodix/code?tab=readme-ov-file#polar_parity_aidedhh

But if we are talking low latency, i.e. even shorter codes, then BCH codes and the OSD (OSLD even) will give you much better results if you have the resources:

https://github.com/aicodix/code?tab=readme-ov-file#osdhh

This is the only free advise I can give you.
