### ISSUE TITLE
stream decoding process

### ISSUE THREAD

**Issue by YD1RUH** [aicodix/modem#3]
hello, this is interesting project.
is it possible to run process decoding with stream process. in example using sox than the ./decode script automatic detected data to decode the signal. if posible, it will be great..

thankyou, 73

**Comment by xdsopl** [comment]
I use something like this for example:
```while arecord -f S16_LE -c 1 -r 48000 - | ./decode - - ; do echo ; sleep 1 ; done```
But of course it would be nice to add a streaming feature, so there is no need to restart the decoder after a decode.

**Comment by YD1RUH** [comment]
Thakyou for the information. I just try another method by put this line `rec audio/recorded.wav rate 8k silence 1 0.1 3% 1 3.0 3%` to infinite loop bash and it work perfectly. 73
