### ISSUE TITLE
'fast'-branch issues

### ISSUE THREAD

**Issue by LieBtrau** [aicodix/modem#5]
Hi Ahmet,

1. It would be very helpful if the readme.md explained what makes this modem different from the other branches.
2. The decoder doesn't build because of the warning that some data might not be initialized:
   * decode.cc, line 471 should probably be : `code_type tmp[mod_max]={0};`
   * decode.cc, line 509 should probably be : `code_type tmp[mod_max]={0};`

I'm using `g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0`

Regards,

Christoph

**Comment by xdsopl** [comment]
The fast branch was created temporarily while experimenting. You can disregard its contents. The main and short branches are the interesting ones.

**Comment by LieBtrau** [comment]
Ok, very well.
