### ISSUE TITLE
encode command options, compatibility with Rattlegram

### ISSUE THREAD

**Issue by ea4gmz** [aicodix/modem#6]
Hello,
This program looks great. Maybe the documentation could be improved. I see encode supports this options:
./encode
usage: ./encode OUTPUT RATE BITS CHANNELS INPUT [OFFSET] [CALLSIGN] [MODE]
I know how to set all parameters except MODE. If I send a message from the computer and monitor it with my smartphone running Rattlegram, I can see something is received, the callsign is decoded, followed by "Mode 6 unsupported". Is it posible to exchange messages between this linux modem for PC and Rattlegram app in a phone?
thank you and best regards

**Comment by xdsopl** [comment]
The modes used in Rattlegram can be found in the ```short``` branch. I agree that the documentation needs improvement.

**Comment by ea4gmz** [comment]
Hello,
That worked. By the way I had to learn about the branches. Excited to see I can send messages from the computer to phone. Thanks a lot, I will play more with this and involve more people. 73
