### ISSUE TITLE
decode program, output information, Es/N0

### ISSUE THREAD

**Issue by ea4gmz** [aicodix/modem#7]
Hello,
When I run decode I obtain this output:
     symbol pos: 2298
     coarse cfo: 1800 Hz
     oper mode: 16
     call sign:    EA4GMZ
     demod .... done
     coarse sfo: -0.243791 ppm
     finer cfo: 1800 Hz
     Es/N0 (dB): 29.2713 29.4451 30.2119 30.7631
     bit flips: 0
(which I found is sent to stderr and can be captured with 2> instead of >)
This information is great. I would just like to know what the four Es/N0 numbers mean. Are they related to four different parts of the packet or four different ways of estimating Es/N0?
regards

**Comment by xdsopl** [comment]
They are the estimated SNR numbers for each OFDM symbol

**Comment by ea4gmz** [comment]
Thanks a lot.

**Comment by ea4gmz** [comment]
Thanks a lot.
